# Generated by Django 6.0.2 on 2026-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created'], 'verbose_name': 'Leadس', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelTable(
            name='lead',
            table='lead',
        ),
    ]
