# Generated by Django 6.0.2 on 2026-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_rename_leads_lead_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'ordering': ['-created'], 'verbose_name': 'Action History', 'verbose_name_plural': 'Action Histories'},
        ),
        migrations.RenameField(
            model_name='actionhistory',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
